/**
 * Creative data models: the copy and visual assets attached to a campaign.
 * Owned/generated by the `creative-studio` module.
 */

export type CreativeTone =
  | 'neutral'
  | 'emotional'
  | 'premium'
  | 'playful'
  | 'urgent'
  | 'seasonal';

export interface Headline {
  id: string;
  text: string;
  tone: CreativeTone;
  isSelected: boolean; // the variant currently attached to the live creative
  createdAt: string; // ISO timestamp
}

export interface Description {
  id: string;
  text: string;
  tone: CreativeTone;
  isSelected: boolean;
  createdAt: string;
}

export type CTAType =
  | 'shop_now'
  | 'learn_more'
  | 'sign_up'
  | 'download'
  | 'get_offer'
  | 'custom';

export interface CallToAction {
  id: string;
  type: CTAType;
  label: string; // rendered text, required when type === 'custom'
  isSelected: boolean;
}

export interface Pin {
  id: string;
  imageUrl?: string; // populated once an asset is attached/generated
  title: string;
  destinationUrl: string;
}

export interface Creative {
  id: string;
  headlines: Headline[];
  descriptions: Description[];
  ctas: CallToAction[];
  pins: Pin[];
  /** Convenience getters are implemented as pure functions in `creative-studio`,
   *  not stored — `isSelected` above is the single source of truth. */
}
